from .action_choice_trader.action_choice_trader import ActionChoiceTrader
from .drmca import TraderDeepReinforcementMonteCarloAgent
from .montecarlo_agent import TraderMonteCarloAgent


class TraderAgent(TraderDeepReinforcementMonteCarloAgent, TraderMonteCarloAgent, ActionChoiceTrader):
	pass
